import numpy as np
from BSPDungeonGeneration import generate_bsp_dungeon
import genetic_dungeon
from renderingCode.rendering import background, corridorCleaner, walls, corridors, addFloors, placeItem
from PIL import Image as PILImage
import os

if __name__ == "__main__":
    # generate dungeon geometry
    MAP_W, MAP_H, ROOMS = 30, 30, 6
    rooms, corridors_list, root = generate_bsp_dungeon(MAP_W, MAP_H, ROOMS, rng_seed=42)

    # run GA to get placements
    best_layout = genetic_dungeon.run_ga(rooms)

    # iitialize rendering environment
    img = background()
    matrix = np.zeros((32, 32))

    # cean corridors to prevent overlap with rooms
    corridorCleaner(corridors_list, rooms)

    # render rooms and corridors
    walls(img, matrix, rooms)
    corridors(img, matrix, corridors_list)
    addFloors(img, rooms)

    # place objects generated by the GA
    placeItem(img, matrix, best_layout)

    # show the result
    img.show()  # opens the dungeon image window
    print("Dungeon rendering is complete")

